In [2]:
import numpy as np

In [3]:
x = np.array([2,5,8])
print(x)
print(x.shape)

[2 5 8]
(3,)


In [4]:
# 1. 转置
print(x.T)
print(x.T.shape)

[2 5 8]
(3,)


In [6]:
# 2. 向量相加
y = np.array([1,3,7])
print(x + y)

[ 3  8 15]


In [7]:
# 3. 向量与标量相乘
print(x * 3)

[ 6 15 24]


In [10]:
# 4. 向量与向量相乘（对位相乘）
print(x * y)

[ 2 15 56]


In [12]:
# 5. 向量点乘
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

73
73
73


In [13]:
# 6. 计算范数
l0_norm = np.linalg.norm(x, ord=0)
print(l0_norm)

3.0


In [14]:
l1_norm = np.linalg.norm(x, ord=1)
print(l1_norm)
l2_norm = np.linalg.norm(x, ord=2)
print(l2_norm)
lp_norm = np.linalg.norm(x, ord=np.inf)
print(lp_norm)

15.0
9.643650760992955
8.0
