In [1]:
import numpy as np

基本矩阵运算

In [2]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,3,7],[5,0,2]])
print(A)
print(A.shape)
print(B)
print(B.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 3 7]
 [5 0 2]]
(2, 3)


In [3]:
# 1. 取矩阵中的某个元素
print(A[0][1])

2


In [4]:
print(A[1])

[4 5 6]


In [5]:
# 2. 转置
print(A.T)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [15]:
# 3. 矩阵相加，需要形状相同
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [7]:
C = np.array([[1,3,7],[5,0,2],[5,6,7]])
print(C.shape)

(3, 3)


In [12]:
# 形状不同不能相加
# print(A + C)

In [14]:
# 矩阵和向量相加
x = np.array([2,5,8])
print(A + x)

[[ 3  7 11]
 [ 6 10 14]]


In [16]:
# 4. 矩阵与标量相乘
print(A * 3)

[[ 3  6  9]
 [12 15 18]]


In [20]:
# 5. 矩阵与向量相乘（向量广播后对位相乘）
print(A * x)

[[ 2 10 24]
 [ 8 25 48]]


In [22]:
# 6. 矩阵与矩阵相乘（对位相乘）
print(A * B)

[[ 1  6 21]
 [20  0 12]]


In [24]:
# 7. 矩阵乘法
print(A.dot(B.T))

[[28 11]
 [61 32]]


In [25]:
print(A @ C)

[[26 21 32]
 [59 48 80]]


In [26]:
# 8. 矩阵求逆
D = np.array([[1,2],[3,5]])
D_inv = np.linalg.inv(D)
print(D_inv)

[[-5.  2.]
 [ 3. -1.]]


In [27]:
print(D @ D_inv)
print(D_inv @ D)

[[1.00000000e+00 2.22044605e-16]
 [4.44089210e-16 1.00000000e+00]]
[[1.00000000e+00 1.99840144e-15]
 [0.00000000e+00 1.00000000e+00]]


In [28]:
D_inv = np.around(D_inv).astype(int)
print(D_inv)

[[-5  2]
 [ 3 -1]]


In [29]:
print(D @ D_inv)
print(D_inv @ D)

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [30]:
A_inv = np.linalg.pinv(A)
print(A)
print(A_inv)

[[1 2 3]
 [4 5 6]]
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [31]:
print(A @ A_inv)
print(A_inv @ A)

[[ 1.00000000e+00  3.60822483e-16]
 [-1.11022302e-15  1.00000000e+00]]
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


其它矩阵运算

In [32]:
# 9. 向量化
print(A.flatten())

[1 2 3 4 5 6]


In [33]:
# 10. 哈达玛积（对位相乘）
print(A * B)
print(np.multiply(A, B))

[[ 1  6 21]
 [20  0 12]]
[[ 1  6 21]
 [20  0 12]]


In [36]:
# 11. 矩阵内积
print(np.sum(A * B))
print(np.dot(A.flatten(), B.flatten()))

60
60


In [37]:
# 12. 克罗内克积
print(A)
print(B)
print(np.kron(A, B))

[[1 2 3]
 [4 5 6]]
[[1 3 7]
 [5 0 2]]
[[ 1  3  7  2  6 14  3  9 21]
 [ 5  0  2 10  0  4 15  0  6]
 [ 4 12 28  5 15 35  6 18 42]
 [20  0  8 25  0 10 30  0 12]]


张量的定义和形状

In [41]:
tensor = np.array([[[1,2],[3,5],[4,8]],[[1,2],[3,5],[4,8]],[[1,2],[3,5],[4,8]]])
print(tensor)
print(tensor.shape)

[[[1 2]
  [3 5]
  [4 8]]

 [[1 2]
  [3 5]
  [4 8]]

 [[1 2]
  [3 5]
  [4 8]]]
(3, 3, 2)


梯度计算

In [42]:
f = np.array([1,2,4,7,11,16])
print(np.gradient(f))

[1.  1.5 2.5 3.5 4.5 5. ]


In [43]:
print(np.gradient(A))

(array([[3., 3., 3.],
       [3., 3., 3.]]), array([[1., 1., 1.],
       [1., 1., 1.]]))
