In [1]:
import numpy as np

In [2]:
# 1. 均匀分布
a = np.random.rand(5)
print(a)

[0.41234736 0.45950368 0.62500168 0.95531392 0.73022398]


In [3]:
a = np.random.rand(2, 3)
print(a)

[[0.36746499 0.57163266 0.38550174]
 [0.50580841 0.94387747 0.97360215]]


In [5]:
b = np.random.randint(0, 100, 5)
print(b)

[56 43 20 32 17]


In [6]:
b = np.random.randint(0, 100, size=(3, 4))
print(b)

[[32 84 30 78]
 [14 86 22 22]
 [50 26 73 91]]


In [7]:
# 2. 正态分布
c = np.random.randn(10)    # 标准正态分布
print(c)

[-1.2774412  -0.34505863 -1.63353295  0.33741038 -1.03027183 -0.47605813
 -0.47645813  0.82983605 -1.31174323  0.13714506]


In [8]:
c = np.random.randn(2, 5)    # 标准正态分布
print(c)

[[-0.86920259 -0.90755205  1.46084096  1.23606361  0.28733324]
 [ 0.50882491  1.10465612 -0.62077032 -0.15638277  0.68259721]]


In [9]:
print(c * 10 + 5)

[[-3.69202593 -4.07552051 19.60840958 17.36063612  7.87333238]
 [10.08824914 16.04656115 -1.20770317  3.43617225 11.82597211]]


In [10]:
d = np.random.normal(5, 10, size=(2,5))
print(d)

[[ 8.92943278  5.5691632   0.02540364 16.90123002  9.86644483]
 [-2.92309899  6.22869257  4.33791562  0.1441064   2.26592972]]
